language: node_js
node_js:
  - "12"
deploy:
  provider: heroku
  app: hacker-news-v1
  api_key:
    secure: hiRN6sihwVVKak7w7f2yZYc2+dsuQqJ8eJlDT2lMofzTleGIDfwxwZLpg9H/baBBLRd2ps1RhX51O5UFdVWFyKI5mOpirSlO3PTdqngEvCxSwHViXY4nRa0GE2n8Ip9KZmi+a74/OgZUp2q+LUyLF5ZuY4zlTfvVB/IcTMAT266K4In+cWvsJvWuderAnpx3a4J1L5XfdUbCrlWP93spzTIlhGr2/TZyeOkUCoA94oiE0BiN/YbfGyixhMBo3iq8/WbRGz1iz1ZdpA7UEGgKdyL/NEXhFYXFUItWjbSoAVGsEBJeeS9NI0fwT9xQyjU4S/uivLSWKvr/Z/hqurberLO48dORIZb9oafiuLNQQrhkmBHO1s18o+sQ5LKvWAB3fRUUMlFH6ej+EFitSJxq1uCV3UeLLgI3bA9a/JBofdOCQfZ7VxTMLEEYAG0bQFnrVm2OVuqc4i3gUmBwaE3FWprWFb60/rNXFae6TwPVXy7j3ow3JldiS8R9KWgvlqndKC1zaeFePPOdzVQZwHR+x87PKPTewvEqKS6qa8F/N60yH+hygvdm6+0xkpP07xOs82x/llgvK6EUoPMwj+YE7u8wtfZLeHZnBqh3zmbWLUsWh2IFPDsULh1yw37CNBvLAlIbTLU2SnBkCiZn9NqC4f23/EHSJm8iZ+g4F9Ay3E8=
